### PR TITLE
PHP-Slim

### PR DESCRIPTION
**Pull request by cgimenes**

### CODE REVIEW

**Comment by urbanadventurer** [comment]
Thanks @cgimenes and congratulations on your first commit 👍 

Could you please send a new pull request but with only the PHP-Slim plugin?

**Comment by cgimenes** [comment]
Done!

**Comment by urbanadventurer** [comment]
LGTM. Thanks @cgimenes. Congratulations on your first commit 🏆 👍

**Comment by cgimenes** [comment]
Thanks for your attention

**Pull request merged**
