### PR TITLE
Updated with new drupal 7.x versions

### PR DESCRIPTION
**Pull request by gboddin**

### CODE REVIEW

**Review by drupol — APPROVED** [review]
:+1:

**Comment by urbanadventurer** [comment]
Thanks @gboddin for updating these! I appreciate it. 👍 
Thanks to @drupol too, did you both work on this?

**Comment by urbanadventurer** [comment]
Please also update the authors section of the plugin to version 0.5, add your name, and a short description of the update you made.

**Comment by drupol** [comment]
Props to @gboddin , I just reviewed it :)

**Comment by gboddin** [comment]
Thanks, will do! I'll send 8.x and 9.x your way. :)

Awesome tool BTW!

**Comment by urbanadventurer** [comment]
I'm looking forward to it @gboddin!

**Pull request merged**
