### PR TITLE
support for IDN domains using gem simpleidn

### PR DESCRIPTION
**Pull request by andrericardo**
Please let me know what you think @urbanadventurer, based on issue #102

### CODE REVIEW

**Comment by urbanadventurer** [comment]
Sorry for the late response. How is the testing, does it always work?
Also, does it fail gracefully if the gem isn't there?

**Comment by janich** [comment]
IDN works with gem installed, but it fails miserably without it.

Test:
root@1:~/ww-idn# gem uninstall simpleidn
Successfully uninstalled simpleidn-0.0.5
root@1:~/ww-idn# ./whatweb --idn -a 4 www.ødegaard.dk
./whatweb:317:in `block in make_target_list': uninitialized constant SimpleIDN (NameError)
        from ./whatweb:297:in `map'
        from ./whatweb:297:in `make_target_list'
        from ./whatweb:914:in `<main>'

**Comment by andrericardo** [comment]
What is the desired behavior if the argument --idn is passed but the gem is not installed?

**Comment by urbanadventurer** [comment]
HI andrericardo,

Sorry for the late response. I haven't spent time on the WhatWeb project in almost a year.

Adding IDN support is a good idea but I don't think it is ready for inclusion into the main branch.

From reading the code I think it needs testing with:
* HTTPS URI prefixes
* URIs with a port

It would also be more user friendly if it displayed a message to the user to tell them that the plugin isn't available and how to install it. Take a look at how the other optional gems are handled.

**Comment by andrericardo** [comment]
Can I have a IDN domain with HTTPS to test it?

So far I tested with
`./whatweb --idn -a 4 --debug reseñas.li https://www.ødegaard.dk 名がドメイン.com`

But added a little bit of code to parse the HTTP or HTTPS and port
`./whatweb --idn --debug reseñas.li www.ødegaard.dk:80 名がドメイン.com:80`

**Comment by urbanadventurer** [comment]
This is a good idea but I think it would be cleaner to implement with the Addressable gem than using SimpleIDN https://github.com/sporkmonger/addressable

**Comment by andrericardo** [comment]
This is so old now... 😕

**Comment by urbanadventurer** [comment]
OK. I'll close this now but leave the IDN issue open. 
I'd like it to work without the --idn option. So if required gems are available it happens automatically. The IDN URLs also have to work whether they are loaded from a file, the commandline, or as a redirect (meta tag, HTTP 301/302).

**Comment by andrericardo** [comment]
Hi @urbanadventurer 

I have implemented with the Addressable gem as suggested here
https://github.com/andrericardo/WhatWeb/tree/idn-support

`$ ./whatweb www.reseñas.li --idn
http://www.xn--reseas-zwa.li/ [200 OK] Content-Language[en], Country[UNITED STATES][US], Drupal, HTML5, HTTPServer[nginx/1.12.2], IP[192.185.225.13], JQuery, MetaGenerator[Drupal 7 (http://drupal.org)], Modernizr, Script[text/javascript], Title[Porque nos gusta hablar de libros ... | Reseñas.li], UncommonHeaders[x-content-type-options,x-generator], nginx[1.12.2]`

`$ ./whatweb http://www.reseñas.li --idn
http://www.xn--reseas-zwa.li/ [200 OK] Content-Language[en], Country[UNITED STATES][US], Drupal, HTML5, HTTPServer[nginx/1.12.2], IP[192.185.225.13], JQuery, MetaGenerator[Drupal 7 (http://drupal.org)], Modernizr, Script[text/javascript], Title[Porque nos gusta hablar de libros ... | Reseñas.li], UncommonHeaders[x-content-type-options,x-generator], nginx[1.12.2]`

Would you consider adding the Addressable gem?

**Comment by andrericardo** [comment]
Tested input:
 www.ødegaard.dk
 名がドメイン.com
 reseñas.li 
 www.ødegaard.dk:80 
 名がドメイン.com:80
 http://www.reseñas.li

Worked fine for this:
$ ./whatweb --idn --input-file=[input.txt](https://github.com/urbanadventurer/WhatWeb/files/1519236/input.txt)

Some errors with -a4
$ ./whatweb --idn -a4 --input-file=input.txt

```
$ ./whatweb --idn -a4 --input-file=input.txt
http://www.xn--degaard-p1a.dk/ ERROR: undefined method `map' for "whatweb=true":String
http://www.xn--degaard-p1a.dk/ ERROR: undefined method `map' for "whatweb=true":String
http://xn--v8jxj3d1dzdz08w.com/ ERROR: undefined method `map' for "whatweb=true":String
http://www.xn--degaard-p1a.dk/ [301 Moved Permanently] Apache[2.2,2.2.15], Country[DENMARK][DK], HTTPServer[CentOS][Apache/2.2.15 (CentOS)], IP[93.191.155.234], PHP[5.3.3], RedirectLocation[http://odegaard.dk], X-Powered-By[PHP/5.3.3]
http://www.xn--degaard-p1a.dk/ [301 Moved Permanently] Apache[2.2,2.2.15], Country[DENMARK][DK], HTTPServer[CentOS][Apache/2.2.15 (CentOS)], IP[93.191.155.234], PHP[5.3.3], RedirectLocation[http://odegaard.dk], X-Powered-By[PHP/5.3.3]
http://www.xn--reseas-zwa.li/ ERROR: undefined method `map' for "whatweb=true":String
http://xn--reseas-zwa.li/ ERROR: undefined method `map' for "whatweb=true":String
http://xn--v8jxj3d1dzdz08w.com/ ERROR: undefined method `map' for "whatweb=true":String
http://odegaard.dk/ ERROR: undefined method `map' for "whatweb=true":String
http://odegaard.dk/ ERROR: undefined method `map' for "whatweb=true":String

http://xn--v8jxj3d1dzdz08w.com/ [200 OK] Apache, Cookies[COOKIE,referrer,t], Country[UNITED STATES][US], HTTPServer[Apache], IP[68.178.213.61], UncommonHeaders[cartoon]
http://odegaard.dk/wp-login.php ERROR: Timed out Net::ReadTimeout
http://www.xn--reseas-zwa.li/ [200 OK] Content-Language[en], Country[UNITED STATES][US], Drupal, HTML5, HTTPServer[nginx/1.12.2], IP[192.185.225.13], JQuery, MetaGenerator[Drupal 7 (http://drupal.org)], Modernizr, Script[text/javascript], Title[Porque nos gusta hablar de libros ... | Reseñas.li], UncommonHeaders[x-content-type-options,x-generator], cPanel, nginx[1.12.2]
http://odegaard.dk/wp-login.php ERROR: Timed out Net::ReadTimeout
```

**Comment by urbanadventurer** [comment]
I've made IDN support and the addressable gem required.

image

**Pull request closed without merging**
